/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wizstom;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Krzysztof
 */
public class ListaPacjentow extends javax.swing.JFrame {

    /**
     * Creates new form pacjenn
     */
    public ListaPacjentow() {
        initComponents();
        setIconImage(WizStomApp.getAppIcon());
    }
    int PozycjaDoUstawienia=-1;
    
    public void UstawPozycje( int Pos)
    {
        PozycjaDoUstawienia = Pos;
    }
    
    public void UkryjWybierz()
    {
        jWybierzButton.setVisible(false);
    }
    
    OkienkoWizyty OkienkoWiz;
    
    public void setOkienkoWizyty( OkienkoWizyty o) {
        OkienkoWiz = o;
    }
    
    public int wczytaj()
    {
        AppSession appses = new AppSession();
        Session session= appses.OpenSession();
        
        String SqlStr;
        String Nazwisko = jNazwiskoField.getText();
        

        SqlStr = "select * from Pacjent where UPPER(nazwisko) like UPPER('"+Nazwisko+"%') order by ID_pacjenta";

        ArrayList<Pacjent> rows = (ArrayList<Pacjent>) session.createSQLQuery(SqlStr).addEntity(Pacjent.class).list();
        
      
        DefaultTableModel tblModel  = (DefaultTableModel)jTable1.getModel();  
        int rowCount = tblModel.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        

        String data[] = new String[7];
        for( Pacjent pat : rows){
            data[0]= Integer.toString(pat.getIdPacjenta());
            data[1]= pat.getImie();
            data[2]= pat.getNazwisko();
            data[3]= pat.getPesel();
            data[4]= pat.getMiejscowosc();
            data[5]= pat.getAdres();
            data[6]= Integer.toString(pat.getTelefon());
            tblModel.addRow(data);
        }
        
        if ( PozycjaDoUstawienia >= 0 )
        {
            jTable1.setRowSelectionInterval(PozycjaDoUstawienia, PozycjaDoUstawienia);
            PozycjaDoUstawienia = -1;
        }
        appses.CloseSession();
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EdytujButton = new javax.swing.JButton();
        UsunButton = new javax.swing.JButton();
        jWybierzButton = new javax.swing.JButton();
        jNazwiskoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSzukajButton = new javax.swing.JButton();
        jDodajButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Pacjenci");
        setBackground(new java.awt.Color(204, 255, 204));
        setLocation(new java.awt.Point(200, 200));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        EdytujButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EdytujButton.setText("Edytuj");
        EdytujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdytujButtonActionPerformed(evt);
            }
        });

        UsunButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsunButton.setText("Usuń");
        UsunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunButtonActionPerformed(evt);
            }
        });

        jWybierzButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jWybierzButton.setText("Wybierz pacjenta");
        jWybierzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWybierzButtonActionPerformed(evt);
            }
        });

        jNazwiskoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nazwisko");

        jSzukajButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSzukajButton.setText("Szukaj");
        jSzukajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSzukajButtonActionPerformed(evt);
            }
        });

        jDodajButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDodajButton.setText("Dodaj nowego pacjenta");
        jDodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajButtonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Imię", "Nazwisko", "PESEL", "Miejscowość", "Adres", "Telefon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setIntercellSpacing(new java.awt.Dimension(1, 3));
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSzukajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDodajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EdytujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jWybierzButton)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSzukajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDodajButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdytujButton)
                    .addComponent(UsunButton)
                    .addComponent(jWybierzButton))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSzukajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSzukajButtonActionPerformed
        wczytaj();
    }//GEN-LAST:event_jSzukajButtonActionPerformed

    private void jDodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajButtonActionPerformed
        // TODO add your handling code here:
        OkienkoPacjenta dp = new OkienkoPacjenta();
        dp.UstawListe(this);
        dp.setVisible(true);
    }//GEN-LAST:event_jDodajButtonActionPerformed

    private void EdytujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdytujButtonActionPerformed

        int Selected = jTable1.getSelectedRow();
        if(Selected >= 0 )
        {   PozycjaDoUstawienia = Selected;
            String IDSelected = jTable1.getModel().getValueAt(Selected, 0).toString();
            AppSession appses = new AppSession();
            Session session= appses.OpenSession();
   

            Pacjent Pat;

            Pat = (Pacjent) session.createSQLQuery("select * from pacjent where ID_Pacjenta="+IDSelected)
            .addEntity(Pacjent.class).uniqueResult();

            OkienkoPacjenta ds = new OkienkoPacjenta();
            ds.UstawPacjenta(Pat);
            ds.UstawListe(this);

            
            appses.CloseSession();

            ds.setVisible(true);

        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz pacjenta", "Wskazówka", JOptionPane.DEFAULT_OPTION);

    }//GEN-LAST:event_EdytujButtonActionPerformed

    private void UsunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunButtonActionPerformed
        int Selected = jTable1.getSelectedRow();

        if(Selected >= 0 )
        {   
           
            int dialogButton= JOptionPane.showConfirmDialog (null, "Czy napewno chcesz usunąć pacjenta wraz z jego wizytami?","Potwierdź",JOptionPane.YES_NO_OPTION);

            if (dialogButton == JOptionPane.YES_OPTION) {
                String IDSelected = jTable1.getModel().getValueAt(Selected, 0).toString();
                AppSession appses = new AppSession();
                Session session= appses.OpenSession();

                Transaction trans = session.beginTransaction();

                Pacjent Pat = new Pacjent();
                Pat.setIDPacjenta(Integer.parseInt(IDSelected));

                session.delete(Pat);

                trans.commit();
            
                appses.CloseSession();
          
                DefaultTableModel tblModel  = (DefaultTableModel)jTable1.getModel();
                tblModel.removeRow(Selected);
            }

        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz pacjenta", "Wskazówka", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_UsunButtonActionPerformed

    private void jWybierzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWybierzButtonActionPerformed
        int Selected = jTable1.getSelectedRow();

        if(Selected >= 0 )
        {   String ID = jTable1.getModel().getValueAt(Selected, 0).toString();
            String Imie = jTable1.getModel().getValueAt(Selected, 1).toString();
            String Nazwisko = jTable1.getModel().getValueAt(Selected, 2).toString();
            OkienkoWiz.WybierzPacjenta( ID, Imie, Nazwisko);
            setVisible(false);
        
        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz pacjenta", "Wskazówka", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_jWybierzButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPacjentow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPacjentow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPacjentow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPacjentow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPacjentow().setVisible(true);
            }
        });
    }
    
    public String getTextField1()
    {
        return jNazwiskoField.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EdytujButton;
    private javax.swing.JButton UsunButton;
    private javax.swing.JButton jDodajButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNazwiskoField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSzukajButton;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jWybierzButton;
    // End of variables declaration//GEN-END:variables
}
