/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wizstom;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Krzysztof
 */
public class ListaWizyt extends javax.swing.JFrame {

    /**
     * Creates new form WizytyStomatologiczne
     */
    public ListaWizyt() {
        initComponents();
        setIconImage(WizStomApp.getAppIcon());
    }

    int PozycjaDoUstawienia=-1;
    
    public void UstawPozycje( int Pos)
    {
        PozycjaDoUstawienia = Pos;
    }
    

    public int wczytaj()
    {
        AppSession appses = new AppSession();
        Session session= appses.OpenSession();
              
        String SqlStr;
        String SqlCol;
        String Nazwisko = jNazwiskoField.getText();
        
        SqlCol = "select ID_wizyty, Data_wizyty, p.nazwisko as nazwisko_pat, p.imie as imie_pat, s.nazwisko, s.imie, zab, kod_diagnozy, kod_uslugi from Wizyta w, Pacjent p, Stomatolog s where p.ID_pacjenta =w.ID_pacjenta and s.ID_stomatologa = w.ID_stomatologa";
        SqlStr = SqlCol +" and UPPER(p.nazwisko) like UPPER('"+Nazwisko+"%') order by ID_wizyty";

        List<Object[]> rows = session.createSQLQuery(SqlStr).list();
        
      
        DefaultTableModel tblModel  = (DefaultTableModel)jTable1.getModel();  
        int rowCount = tblModel.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        

        String data[] = new String[7];
        for(Object[] row : rows){
            data[0]=row[0].toString();
            DateFormat dateFormat = new SimpleDateFormat("dd.MM.yy");  
            if( row[1] != null )
                data[1]= dateFormat.format((Date)row[1]); 
            else
                data[1]="";
            data[2]=row[2].toString()+" "+row[3].toString();
            data[3]=row[4].toString()+" "+row[5].toString();

            data[4]=row[6].toString();
            data[5]=row[7].toString();
            data[6]=row[8].toString();
            tblModel.addRow(data);
        }
        
        if ( PozycjaDoUstawienia >= 0 )
        {
            jTable1.setRowSelectionInterval(PozycjaDoUstawienia, PozycjaDoUstawienia);
            PozycjaDoUstawienia = -1;
        }
        appses.CloseSession();
    
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPatButton = new javax.swing.JButton();
        jStomButton = new javax.swing.JButton();
        jDiagButton = new javax.swing.JButton();
        jUzyButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jUslButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jNazwiskoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSzukajButton = new javax.swing.JButton();
        DodajWizyte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EdytujButton = new javax.swing.JButton();
        UsunButton = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wizyty Stomatologiczne");
        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(204, 255, 204));
        setLocation(new java.awt.Point(0, 100));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(235, 32767));

        jPatButton.setBackground(new java.awt.Color(255, 255, 204));
        jPatButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPatButton.setText("Pacjenci");
        jPatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatButtonActionPerformed(evt);
            }
        });

        jStomButton.setBackground(new java.awt.Color(255, 255, 204));
        jStomButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jStomButton.setText("Stomatolodzy");
        jStomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStomButtonActionPerformed(evt);
            }
        });

        jDiagButton.setBackground(new java.awt.Color(255, 255, 204));
        jDiagButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDiagButton.setText("Diagnozy");
        jDiagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiagButtonActionPerformed(evt);
            }
        });

        jUzyButton.setBackground(new java.awt.Color(255, 255, 204));
        jUzyButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUzyButton.setText("Użytkownicy");
        jUzyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUzyButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wizstom/Zab.png"))); // NOI18N

        jUslButton1.setBackground(new java.awt.Color(255, 255, 204));
        jUslButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUslButton1.setText("Usługi");
        jUslButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUslButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUslButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jStomButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDiagButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jUzyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jPatButton)
                .addGap(18, 18, 18)
                .addComponent(jStomButton)
                .addGap(26, 26, 26)
                .addComponent(jDiagButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUzyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUslButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1134, 515));

        jNazwiskoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nazwisko");

        jSzukajButton.setBackground(new java.awt.Color(255, 255, 204));
        jSzukajButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSzukajButton.setText("Szukaj");
        jSzukajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSzukajButtonActionPerformed(evt);
            }
        });

        DodajWizyte.setBackground(new java.awt.Color(255, 255, 204));
        DodajWizyte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DodajWizyte.setText("Umów nową wizytę");
        DodajWizyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajWizyteActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data Wizyty", "Pacjent", "Stomatolog", "Ząb", "Diagnoza", "Usługa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        EdytujButton.setBackground(new java.awt.Color(255, 255, 204));
        EdytujButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EdytujButton.setText("Edytuj");
        EdytujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdytujButtonActionPerformed(evt);
            }
        });

        UsunButton.setBackground(new java.awt.Color(255, 255, 204));
        UsunButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsunButton.setText("Usuń");
        UsunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DodajWizyte)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jSzukajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EdytujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UsunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSzukajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(DodajWizyte)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdytujButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSzukajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSzukajButtonActionPerformed
        wczytaj();
    }//GEN-LAST:event_jSzukajButtonActionPerformed

    private void DodajWizyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajWizyteActionPerformed
        OkienkoWizyty ds = new OkienkoWizyty();
        Wizyta Wiz = new Wizyta();
        long millis=System.currentTimeMillis();  
        Wiz.setDataWizyty(new Date(millis));
        ds.UstawWizyte(Wiz);
        ds.UstawListe(this);
        ds.setVisible(true);
        ds.UkryjPolaDlaNowejWizyty();

    }//GEN-LAST:event_DodajWizyteActionPerformed

    private void EdytujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdytujButtonActionPerformed

        int Selected = jTable1.getSelectedRow();
        if(Selected >= 0 )
        {   PozycjaDoUstawienia = Selected;
            String IDSelected = jTable1.getModel().getValueAt(Selected, 0).toString();
            
            AppSession appses = new AppSession();
            Session session= appses.OpenSession();


            Wizyta Wiz;

            Wiz = (Wizyta) session.createSQLQuery("select * from wizyta where ID_Wizyty="+IDSelected)
            .addEntity(Wizyta.class).uniqueResult();
            Wiz.setPacjent(jTable1.getModel().getValueAt(Selected, 2).toString());
            Wiz.setStomatolog(jTable1.getModel().getValueAt(Selected, 3).toString());

            OkienkoWizyty ds = new OkienkoWizyty();
            ds.UstawWizyte(Wiz);
            ds.UstawListe(this);

            appses.CloseSession();
 
             ds.setVisible(true);

        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz wizytę", "Wskazówka", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_EdytujButtonActionPerformed

    private void UsunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunButtonActionPerformed
        int Selected = jTable1.getSelectedRow();

        if(Selected >= 0 )
        {   
            int dialogButton= JOptionPane.showConfirmDialog (null, "Czy napewno chcesz usunąć?","Potwierdź",JOptionPane.YES_NO_OPTION);

            if (dialogButton == JOptionPane.YES_OPTION) {
                String IDSelected = jTable1.getModel().getValueAt(Selected, 0).toString();
        
                AppSession appses = new AppSession();
                Session session= appses.OpenSession();
                Transaction trans = session.beginTransaction();

                Wizyta Wiz = new Wizyta();
                Wiz.setIDWizyty(Integer.parseInt(IDSelected));

                session.delete(Wiz);

                trans.commit();
                appses.CloseSession();

                DefaultTableModel tblModel  = (DefaultTableModel)jTable1.getModel();
                tblModel.removeRow(Selected);
            }

        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz wizytę", "Wskazówka", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_UsunButtonActionPerformed

    private void jPatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatButtonActionPerformed
        ListaPacjentow pt = new ListaPacjentow();
        pt.wczytaj();
        pt.UkryjWybierz();
        pt.setVisible(true);
    }//GEN-LAST:event_jPatButtonActionPerformed

    private void jStomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStomButtonActionPerformed
               
        ListaStomatologow sd = new ListaStomatologow();
        sd.UkryjWybierz();
        sd.wczytaj();
        sd.setVisible(true);
    }//GEN-LAST:event_jStomButtonActionPerformed

    private void jDiagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiagButtonActionPerformed
        ListaDiagnoz dd = new ListaDiagnoz();
        dd.UkryjWybierz();
        dd.wczytaj();
        dd.setVisible(true);
    }//GEN-LAST:event_jDiagButtonActionPerformed

    private void jUzyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUzyButtonActionPerformed
        ListaUzytkownikow uz = new ListaUzytkownikow();
        uz.UkryjWybierz();
        uz.wczytaj();
        uz.setVisible(true);
    }//GEN-LAST:event_jUzyButtonActionPerformed

    private void jUslButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUslButton1ActionPerformed
        ListaUslug ud = new ListaUslug();
        ud.UkryjWybierz();
        ud.wczytaj();
        ud.setVisible(true);
    }//GEN-LAST:event_jUslButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaWizyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaWizyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaWizyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaWizyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaWizyt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajWizyte;
    private javax.swing.JButton EdytujButton;
    private javax.swing.JButton UsunButton;
    private javax.swing.JButton jDiagButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jNazwiskoField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jPatButton;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jStomButton;
    private javax.swing.JButton jSzukajButton;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jUslButton1;
    private javax.swing.JButton jUzyButton;
    // End of variables declaration//GEN-END:variables
}
