
package wizstom;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Transaction;


public class ListaUzytkownikow extends javax.swing.JFrame {

    
    
    public ListaUzytkownikow() {
        initComponents();
        setIconImage(WizStomApp.getAppIcon());
 
    }
    
    int PozycjaDoUstawienia=-1;
    
    public void UstawPozycje( int Pos)
    {
        PozycjaDoUstawienia = Pos;
    }
    
    public void UkryjWybierz()
    {
        jWybierzButton.setVisible(false);
    }
    
    OkienkoWizyty OkienkoWiz;
    
    public void setOkienkoWizyty( OkienkoWizyty o) {
        OkienkoWiz = o;
    }

    public int wczytaj()
    {
        AppSession appses = new AppSession();
        Session session= appses.OpenSession();
        
        String SqlStr;
        String Nazwisko = jNazwiskoField.getText();
        
        SqlStr = "select * from Uzytkownik where UPPER(nazwisko) like UPPER('"+Nazwisko+"%') order by ID_uzytkownika";

        ArrayList<Uzytkownik> rows = (ArrayList<Uzytkownik>) session.createSQLQuery(SqlStr).addEntity(Uzytkownik.class).list();
        
      
        DefaultTableModel tblModel  = (DefaultTableModel)jTable1.getModel();  
        int rowCount = tblModel.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        

        String data[] = new String[4];
        for( Uzytkownik uzyt : rows){
            data[0]= Integer.toString(uzyt.getIdUzytkownika());
            data[1]=uzyt.getImieUzytkownika();
            data[2]=uzyt.getNazwiskoUzytkownika();
            data[3]=uzyt.getLoginUzytkownika();
            tblModel.addRow(data);
        }
        
        if ( PozycjaDoUstawienia >= 0 )
        {
            jTable1.setRowSelectionInterval(PozycjaDoUstawienia, PozycjaDoUstawienia);
            PozycjaDoUstawienia = -1;
        }
        appses.CloseSession();
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jNazwiskoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSzukajButton = new javax.swing.JButton();
        DodajStom = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EdytujButton = new javax.swing.JButton();
        UsunButton = new javax.swing.JButton();
        jWybierzButton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Uzytkownicy");
        setLocation(new java.awt.Point(200, 200));
        setName("Stomatolodzy"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jNazwiskoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jNazwiskoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNazwiskoFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Nazwisko");

        jSzukajButton.setText("Szukaj");
        jSzukajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSzukajButtonActionPerformed(evt);
            }
        });

        DodajStom.setText("Dodaj");
        DodajStom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajStomActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Imię", "Nazwisko", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        EdytujButton.setText("Edytuj");
        EdytujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdytujButtonActionPerformed(evt);
            }
        });

        UsunButton.setText("Usuń");
        UsunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunButtonActionPerformed(evt);
            }
        });

        jWybierzButton.setText("Wybierz");
        jWybierzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWybierzButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSzukajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DodajStom, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(EdytujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(UsunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jWybierzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1))
                            .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSzukajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DodajStom)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdytujButton)
                    .addComponent(UsunButton)
                    .addComponent(jWybierzButton))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DodajStomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajStomActionPerformed
      OkienkoUzytkownika ds = new OkienkoUzytkownika();
        ds.UstawListe(this);
        ds.setVisible(true);
       
        
        
    }//GEN-LAST:event_DodajStomActionPerformed

    
    public String getTextField1()
    {
        return jNazwiskoField.getText();
    }
    private void jNazwiskoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNazwiskoFieldActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jNazwiskoFieldActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void EdytujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdytujButtonActionPerformed
   
        
        int Selected = jTable1.getSelectedRow();
        if(Selected >= 0 )
        {   PozycjaDoUstawienia = Selected;
            String IDSelected = jTable1.getModel().getValueAt(Selected, 0).toString(); 
            AppSession appses = new AppSession();
            Session session= appses.OpenSession();
            
           Uzytkownik Uzyt;

           Uzyt = (Uzytkownik) session.createSQLQuery("select * from Uzytkownik where ID_Uzytkownika="+IDSelected)
                    .addEntity(Uzytkownik.class).uniqueResult();
            
            OkienkoUzytkownika ds = new OkienkoUzytkownika();
            ds.UstawUzytkownika(Uzyt);
            ds.UstawListe(this);
            
            appses.CloseSession();
            ds.setVisible(true);
            
       
                    

        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz uzytkownika", "Wskazówka", JOptionPane.DEFAULT_OPTION);
     
 
    }//GEN-LAST:event_EdytujButtonActionPerformed

    private void jSzukajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSzukajButtonActionPerformed
        wczytaj();
    }//GEN-LAST:event_jSzukajButtonActionPerformed

    private void UsunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunButtonActionPerformed
         int Selected = jTable1.getSelectedRow();
         
        if(Selected >= 0 )
        {   
            int dialogButton= JOptionPane.showConfirmDialog (null, "Czy napewno chcesz usunąć?","Warning",JOptionPane.YES_NO_OPTION);

            if (dialogButton == JOptionPane.YES_OPTION) {
                String IDSelected = jTable1.getModel().getValueAt(Selected, 0).toString(); 
                AppSession appses = new AppSession();
                Session session= appses.OpenSession();
                 
                Transaction transaction2 = session.beginTransaction();    
            
                Uzytkownik Uzyt = new Uzytkownik();
                Uzyt.setIDUzytkownika(Integer.parseInt(IDSelected));  
            
                session.delete(Uzyt);
   
                transaction2.commit(); 
                appses.CloseSession();
                DefaultTableModel tblModel  = (DefaultTableModel)jTable1.getModel(); 
                tblModel.removeRow(Selected);
            }

        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz uzytkownika", "Wskazówka", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_UsunButtonActionPerformed

    private void jWybierzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWybierzButtonActionPerformed
        int Selected = jTable1.getSelectedRow();

        if(Selected >= 0 )
        {   String ID = jTable1.getModel().getValueAt(Selected, 0).toString();
            String Imie = jTable1.getModel().getValueAt(Selected, 1).toString();
            String Nazwisko = jTable1.getModel().getValueAt(Selected, 2).toString();
            String Login = jTable1.getModel().getValueAt(Selected, 3).toString();
            String Haslo = jTable1.getModel().getValueAt(Selected, 4).toString();
            //OkienkoWiz.WybierzUzytkownika( ID, Imie, Nazwisko);
            setVisible(false);
        
        }
        else
            JOptionPane.showConfirmDialog(null, "Wybierz stomatologa", "Wskazówka", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_jWybierzButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaUzytkownikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaUzytkownikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaUzytkownikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaUzytkownikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaUzytkownikow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajStom;
    private javax.swing.JButton EdytujButton;
    private javax.swing.JButton UsunButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JTextField jNazwiskoField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSzukajButton;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jWybierzButton;
    // End of variables declaration//GEN-END:variables
}
