/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wizstom;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.hibernate.Session;
import org.hibernate.Transaction;


/**
 *
 * @author Krzysztof
 */
public class OkienkoStomatologa extends javax.swing.JFrame {

    /**
     * Creates new form DodajStomatologa
     */
    public OkienkoStomatologa() {
        initComponents();
        setIconImage(WizStomApp.getAppIcon());
        jIDField.setVisible( false);
    }
    ListaStomatologow ListaStom;
    
    public void UstawListe( ListaStomatologow l)
    { 
        ListaStom = l;
    }
      
    
    public void UstawStomatologa( Stomatolog Stom)
    {
        jIDField.setText(Integer.toString(Stom.getIdStomatologa()));
        jTelField.setText(Integer.toString(Stom.getTelefonStomatologa()));
        jImieField.setText(Stom.getImieStomatologa());
        jNazwiskoField.setText(Stom.getNazwiskoStomatologa());
        jAktywny.setSelected(Stom.getAktywny());
    }
 
    public void AktywujStomatologa()
    {
        jAktywny.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ZapiszButton = new javax.swing.JButton();
        AnulujButton = new javax.swing.JButton();
        jIDField = new javax.swing.JTextField();
        jImieField = new javax.swing.JTextField();
        jNazwiskoField = new javax.swing.JTextField();
        jTelField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jAktywny = new javax.swing.JCheckBox();

        setTitle("Stomatolog");
        setLocation(new java.awt.Point(560, 100));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        ZapiszButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ZapiszButton.setText("Zapisz");
        ZapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapiszButtonActionPerformed(evt);
            }
        });

        AnulujButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AnulujButton.setText("Anuluj");
        AnulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnulujButtonActionPerformed(evt);
            }
        });

        jIDField.setEditable(false);
        jIDField.setBackground(new java.awt.Color(204, 255, 255));
        jIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jIDField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jImieField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jNazwiskoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTelField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Imię");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nazwisko");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Telefon");

        jAktywny.setText("aktywny");
        jAktywny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAktywnyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(AnulujButton)
                        .addGap(28, 28, 28)
                        .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(ZapiszButton)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAktywny)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jNazwiskoField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jImieField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTelField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jImieField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jAktywny)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnulujButton)
                    .addComponent(ZapiszButton)
                    .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapiszButtonActionPerformed
                
        Stomatolog stom = new Stomatolog();
               
        String IDStr =jIDField.getText();
        int Id = 0;
        
        if( !IDStr.isEmpty())
        {
            Id = Integer.parseInt(IDStr);
            stom.setIDStomatologa(Id);
        }
               
        stom.setImieStomatologa(jImieField.getText());
        stom.setNazwiskoStomatologa(jNazwiskoField.getText());
        stom.setAktywny(jAktywny.isSelected());
        
        String TelStr = jTelField.getText();
        if( ! TelStr.isEmpty()) {
            int Tel=Integer.parseInt(TelStr);
            stom.setTelefonStomatologa(Tel);
        }     
        
        if( stom.sprawdzDane()) {
        
            AppSession appses = new AppSession();
            Session session= appses.OpenSession();
        
        
            Transaction trans = session.beginTransaction();     
            if ( Id==0)
                session.save(stom);  
            else
                session.update(stom);
            trans.commit();   
        
            appses.CloseSession();

            setVisible(false);
            ListaStom.wczytaj();
        }       
    }//GEN-LAST:event_ZapiszButtonActionPerformed

    private void AnulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnulujButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_AnulujButtonActionPerformed

    private void jAktywnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAktywnyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAktywnyActionPerformed

    public void ustaw(){
       
       
       
       
               ZapiszButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
            
              
                 
            }
        });
       
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OkienkoStomatologa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OkienkoStomatologa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OkienkoStomatologa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OkienkoStomatologa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OkienkoStomatologa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnulujButton;
    private javax.swing.JButton ZapiszButton;
    private javax.swing.JCheckBox jAktywny;
    private javax.swing.JTextField jIDField;
    private javax.swing.JTextField jImieField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNazwiskoField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTelField;
    // End of variables declaration//GEN-END:variables
}
