/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wizstom;

import org.hibernate.Session;
import org.hibernate.Transaction;

public class OkienkoDiagnozy extends javax.swing.JFrame {

    /**
     * Creates new form DodajDiagnoze
     */
    public OkienkoDiagnozy() {
        initComponents();
        setIconImage(WizStomApp.getAppIcon());
    ;
    }
    ListaDiagnoz ListaDiag;
    
    public void UstawListe( ListaDiagnoz l)
    { 
        ListaDiag = l;
    }
      
    
    public void UstawDiagnoze( Diagnoza Diag)
    {
        jKodField.setText(Diag.getKodDiagnozy());
        jOpisField.setText(Diag.getOpisDiagnozy());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jKodField = new javax.swing.JTextField();
        jZapiszButton = new javax.swing.JButton();
        jAnulujButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOpisField = new javax.swing.JTextArea();

        setTitle("Diagnoza");
        setLocation(new java.awt.Point(560, 100));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jKodField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jZapiszButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jZapiszButton.setText("Zapisz");
        jZapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZapiszButtonActionPerformed(evt);
            }
        });

        jAnulujButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAnulujButton.setText("Anuluj");
        jAnulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnulujButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kod diagnozy");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Opis");

        jOpisField.setColumns(20);
        jOpisField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jOpisField.setRows(5);
        jScrollPane1.setViewportView(jOpisField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jAnulujButton)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jZapiszButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jKodField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jZapiszButton)
                    .addComponent(jAnulujButton))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jZapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZapiszButtonActionPerformed
        
        Diagnoza diag = new Diagnoza();
        
        diag.setKodDiagnozy(jKodField.getText());
        diag.setOpisDiagnozy(jOpisField.getText());

        if( diag.sprawdzDane()) {
            AppSession appses = new AppSession();
            Session session= appses.OpenSession();
                
            Transaction transaction2 = session.beginTransaction();     
            session.saveOrUpdate(diag);
        
            transaction2.commit();   
        
            appses.CloseSession();

            setVisible(false);
            ListaDiag.wczytaj();
        }
    }//GEN-LAST:event_jZapiszButtonActionPerformed

    private void jAnulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnulujButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_jAnulujButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OkienkoDiagnozy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OkienkoDiagnozy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OkienkoDiagnozy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OkienkoDiagnozy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OkienkoDiagnozy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAnulujButton;
    private javax.swing.JTextField jKodField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jOpisField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jZapiszButton;
    // End of variables declaration//GEN-END:variables
}
