
package wizstom;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hibernate.Session;
import org.hibernate.Transaction;
public class OkienkoPacjenta extends javax.swing.JFrame {

    /**
     * Creates new form DodajPacjenta
     */
    public OkienkoPacjenta() {
        initComponents();
        setIconImage(WizStomApp.getAppIcon());
        jIDField.setVisible(false);
    }
   ListaPacjentow ListaPat;
    
    public void UstawListe( ListaPacjentow l)
    { 
        ListaPat = l;
    }
      
    
    public void UstawPacjenta( Pacjent Pat)
    {
        jIDField.setText(Integer.toString(Pat.getIdPacjenta()));
        jImieField.setText(Pat.getImie());
        jNazwiskoField.setText(Pat.getNazwisko());
        jPeselField.setText(Pat.getPesel());
        if( Pat.getDataUr() != null)
        {   DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");  
            String strDate = dateFormat.format(Pat.getDataUr());  
            jDataUrField.setText(strDate);
        }
        jMiejscowoscField.setText(Pat.getMiejscowosc());
        jAdresField.setText(Pat.getAdres());
        jKodPocztowyField.setText(Pat.getKodPocztowy());
        jTelField.setText(Integer.toString(Pat.getTelefon()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jImieField = new javax.swing.JTextField();
        jDataUrField = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jNazwiskoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jIDField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jZapiszButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jAnulujButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jAdresField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jKodPocztowyField = new javax.swing.JTextField();
        jMiejscowoscField = new javax.swing.JTextField();
        jPeselField = new javax.swing.JFormattedTextField();
        jTelField = new javax.swing.JFormattedTextField();

        setTitle("Pacjent");
        setLocation(new java.awt.Point(560, 100));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Telefon");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("PESEL");

        jImieField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDataUrField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jDataUrField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kod pocztowy");

        jNazwiskoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Miejscowość");

        jIDField.setBackground(new java.awt.Color(204, 255, 255));
        jIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jIDField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jIDField.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Data urodzenia");

        jZapiszButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jZapiszButton.setText("Zapisz");
        jZapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZapiszButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Adres");

        jAnulujButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAnulujButton.setText("Anuluj");
        jAnulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnulujButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Imię");

        jAdresField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nazwisko");

        jKodPocztowyField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMiejscowoscField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            jPeselField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPeselField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTelField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########"))));
        jTelField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jAnulujButton)
                        .addGap(18, 18, 18)
                        .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jZapiszButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jNazwiskoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jImieField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAdresField)
                            .addComponent(jMiejscowoscField)
                            .addComponent(jKodPocztowyField)
                            .addComponent(jDataUrField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jPeselField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTelField))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jImieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jPeselField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jDataUrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jAdresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMiejscowoscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jKodPocztowyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jZapiszButton)
                    .addComponent(jAnulujButton)
                    .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAnulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnulujButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jAnulujButtonActionPerformed

    private void jZapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZapiszButtonActionPerformed
        Pacjent pat = new Pacjent();
 
        String IDStr =jIDField.getText();
        int Id = 0;
        
        if( !IDStr.isEmpty())
        {
            Id = Integer.parseInt(IDStr);
            pat.setIDPacjenta(Id);
        }
        
        
        pat.setImie(jImieField.getText());
        pat.setNazwisko(jNazwiskoField.getText());
        
        String StrDataUr= jDataUrField.getText();
        if( ! StrDataUr.isEmpty()) {         
            Date DataUr;
         try {
             DataUr = new SimpleDateFormat("dd.MM.yyyy").parse(jDataUrField.getText());
              pat.setDataUr(DataUr);
           } catch (ParseException ex) {
               Logger.getLogger(OkienkoPacjenta.class.getName()).log(Level.SEVERE, null, ex);
           }
        }

        pat.setPesel(jPeselField.getText());
        pat.setAdres(jAdresField.getText());
        pat.setMiejscowosc(jMiejscowoscField.getText());
        pat.setKodPocztowy(jKodPocztowyField.getText());
        String TelStr = jTelField.getText();
        if( ! TelStr.isEmpty()) {
          int Tel=Integer.parseInt(TelStr);       
          pat.setTelefon(Tel);
        }
        
        if( pat.sprawdzDane()) {      
            AppSession appses = new AppSession();
            Session session= appses.OpenSession();      
        
            Transaction trans = session.beginTransaction();     
            if ( Id==0)
                session.save(pat);  
            else
                session.update(pat);
            trans.commit();   
        
            appses.CloseSession();

            setVisible(false);
            
            ListaPat.wczytaj();
        }
        
    }//GEN-LAST:event_jZapiszButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OkienkoPacjenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OkienkoPacjenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OkienkoPacjenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OkienkoPacjenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OkienkoPacjenta().setVisible(true);
            }
        });
    }
    
     public void ustaw(){
       
       
       
       
               jZapiszButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
            
              
                 
            }
        });
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAdresField;
    private javax.swing.JButton jAnulujButton;
    private javax.swing.JFormattedTextField jDataUrField;
    private javax.swing.JTextField jIDField;
    private javax.swing.JTextField jImieField;
    private javax.swing.JTextField jKodPocztowyField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMiejscowoscField;
    private javax.swing.JTextField jNazwiskoField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jPeselField;
    private javax.swing.JFormattedTextField jTelField;
    private javax.swing.JButton jZapiszButton;
    // End of variables declaration//GEN-END:variables
}
