/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wizstom;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.hibernate.Session;
import org.hibernate.Transaction;


/**
 *
 * @author Krzysztof
 */
public class OkienkoUzytkownika extends javax.swing.JFrame {

    /**
     * Creates new form DodajUzytkownika
     */
    public OkienkoUzytkownika() {
        initComponents();
        setIconImage(WizStomApp.getAppIcon());
        jIDField.setVisible( false);
    }
    ListaUzytkownikow ListaUzyt;
    
    public void UstawListe( ListaUzytkownikow l)
    { 
        ListaUzyt = l;
    }
      
    
    public void UstawUzytkownika( Uzytkownik Uzyt)
    {
        jIDField.setText(Integer.toString(Uzyt.getIdUzytkownika()));
        jImieField.setText(Uzyt.getImieUzytkownika());
        jNazwiskoField.setText(Uzyt.getNazwiskoUzytkownika());
        jLogin.setText(Uzyt.getLoginUzytkownika());
        jHaslo.setText(Uzyt.getHasloUzytkownika());
        jAdministrator.setSelected(Uzyt.getAdministrator());
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ZapiszButton = new javax.swing.JButton();
        AnulujButton = new javax.swing.JButton();
        jIDField = new javax.swing.JTextField();
        jImieField = new javax.swing.JTextField();
        jNazwiskoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelHaslo = new javax.swing.JLabel();
        jLogin = new javax.swing.JTextField();
        jHaslo = new javax.swing.JTextField();
        jAdministrator = new javax.swing.JCheckBox();

        setTitle("Uzytkownik");
        setLocation(new java.awt.Point(560, 100));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        ZapiszButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ZapiszButton.setText("Zapisz");
        ZapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapiszButtonActionPerformed(evt);
            }
        });

        AnulujButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AnulujButton.setText("Anuluj");
        AnulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnulujButtonActionPerformed(evt);
            }
        });

        jIDField.setEditable(false);
        jIDField.setBackground(new java.awt.Color(204, 255, 255));
        jIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jIDField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jImieField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jNazwiskoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Imię");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nazwisko");

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogin.setText("Login");

        jLabelHaslo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHaslo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHaslo.setText("Haslo");

        jLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jHaslo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jAdministrator.setText("Administrator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHaslo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jNazwiskoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jImieField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLogin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHaslo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jAdministrator)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AnulujButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ZapiszButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jImieField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHaslo))
                .addGap(18, 18, 18)
                .addComponent(jAdministrator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnulujButton)
                    .addComponent(ZapiszButton))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapiszButtonActionPerformed
                
        Uzytkownik uzyt = new Uzytkownik();
               
        String IDStr =jIDField.getText();
        int Id = 0;
        
        if( !IDStr.isEmpty())
        {
            Id = Integer.parseInt(IDStr);
            uzyt.setIDUzytkownika(Id);
        }
               
        uzyt.setImieUzytkownika(jImieField.getText());
        uzyt.setNazwiskoUzytkownika(jNazwiskoField.getText());
        uzyt.setLoginUzytkownika(jLogin.getText());
        uzyt.setHasloUzytkownika(jHaslo.getText());
        uzyt.setAdministrator(jAdministrator.isSelected());
        
        
        if( uzyt.sprawdzDane()) {
        
            AppSession appses = new AppSession();
            Session session= appses.OpenSession();
        
        
            Transaction trans = session.beginTransaction();     
            if ( Id==0)
                session.save(uzyt);  
            else
                session.update(uzyt);
            trans.commit();   
        
            appses.CloseSession();

            setVisible(false);
            ListaUzyt.wczytaj();
        }       
    }//GEN-LAST:event_ZapiszButtonActionPerformed

    private void AnulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnulujButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_AnulujButtonActionPerformed

    public void ustaw(){
       
       
       
       
               ZapiszButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
            
              
                 
            }
        });
       
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OkienkoUzytkownika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OkienkoUzytkownika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OkienkoUzytkownika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OkienkoUzytkownika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OkienkoUzytkownika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnulujButton;
    private javax.swing.JButton ZapiszButton;
    private javax.swing.JCheckBox jAdministrator;
    private javax.swing.JTextField jHaslo;
    private javax.swing.JTextField jIDField;
    private javax.swing.JTextField jImieField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelHaslo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JTextField jLogin;
    private javax.swing.JTextField jNazwiskoField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
